<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Jayarees-MacBook-Pro.local" name="Stepdef.Register_from_cricketer_first_use_notice" tests="6" failures="1" timestamp="26 Mar 2019 11:58:13 GMT" time="184.373" errors="0">
  <testcase name="i_am_not_a_user_of_agate_on_cricketer_and_I_open_a_browser" time="1.802" classname="Stepdef.Register_from_cricketer_first_use_notice"/>
  <testcase name="i_navigate_to_a_premium_article_on_cricketer" time="11.729" classname="Stepdef.Register_from_cricketer_first_use_notice"/>
  <testcase name="i_click_on_the_create_wallet_button" time="18.040" classname="Stepdef.Register_from_cricketer_first_use_notice"/>
  <testcase name="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page" time="22.041" classname="Stepdef.Register_from_cricketer_first_use_notice"/>
  <testcase name="i_enter_all_the_details_successfully" time="59.270" classname="Stepdef.Register_from_cricketer_first_use_notice"/>
  <testcase name="i_am_registered_as_an_agate_user_on_cricketer_successfully_and_I_am_shown_a_first_use_notice" time="71.491" classname="Stepdef.Register_from_cricketer_first_use_notice">
    <failure type="java.lang.AssertionError" message="expected:&lt;0.25&gt; but was:&lt;0.30000000000000004&gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.25> but was:<0.30000000000000004>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Register_from_cricketer_first_use_notice.i_am_registered_as_an_agate_user_on_cricketer_successfully_and_I_am_shown_a_first_use_notice(Register_from_cricketer_first_use_notice.java:220)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- i_am_registered_as_an_agate_user_on_cricketer_successfully_and_I_am_shown_a_first_use_notice -->
</testsuite> <!-- Stepdef.Register_from_cricketer_first_use_notice -->
